ERROR: error1b.vp:7: port `a' not found in module `sub_internal'
       module `sub_internal' defined at error1b.vp:13
ERROR: error1b.vp:9: port `a' not found in module `sub'
       module `sub' defined at sub.v:4
Exiting after connectivity analysis due to errors
Preprocessor output not saved because error1b.v.preprocessed already exists
